openapi: 3.0.1
info:
  title: Audio Control API
  description: API For controlling audio on Blackmagic Design Cameras
  version: 0.1.0
servers:
- url: /control/api/v1
paths:
  /audio/channels:
    get:
      summary: Get the total number of audio channels available
      responses:
        '200':
          description: Returns the total number of channels
          content:
            application/json:
              schema:
                type: object
                properties:
                  channels:
                    type: integer
                    description: Total number of audio channels available
  /audio/supportedInputs:
    get:
      summary: Get the list of supported audio inputs
      responses:
        '200':
          description: List of all supported audio inputs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                  description: A supported audio input
  /audio/channel/{channelIndex}/input:
    get:
      summary: Get the audio input (source and type) for the selected channel
      parameters:
        - name: channelIndex
          in: path
          description: The index of the channel that its input is being controlled. (Channels index from 0)
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Currently selected input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/input'
        '404':
          description: Channel does not exist
    put:
      summary: Set the audio input for the selected channel
      parameters:
        - name: channelIndex
          in: path
          description: The index of the channel that its input is being controlled. (Channels index from 0)
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/input'
      responses:
        '204':
          description: No Content
        '400':
          description: Invalid audio input
        '404':
          description: Channel does not exist
  /audio/channel/{channelIndex}/input/description:
    get:
      summary: Get the description of the current input of the selected channel
      parameters:
        - name: channelIndex
          in: path
          description: The index of the channel that its input is being controlled. (Channels index from 0)
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Description of the current input of the selected channel
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inputDescription'
        '404':
          description: Channel does not exist
  /audio/channel/{channelIndex}/supportedInputs:
    get:
      summary: Get the list of supported inputs and their availability to switch to for the selected channel
      parameters:
        - name: channelIndex
          in: path
          description: The index of the channel that its supported inputs are being queried. (Channels index from 0)
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: The list of supported inputs
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    input:
                      type: string
                      description: Input name
                    available:
                      type: boolean
                      description: Is the input available to be switched into from the current input for the selected channel
        '404':
          description: Channel does not exist
  /audio/channel/{channelIndex}/level:
    get:
      summary: Get the audio input level for the selected channel
      parameters:
        - name: channelIndex
          in: path
          description: The index of the channel that its input is being controlled. (Channels index from 0)
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Currently set level for the selected channel
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/level'
        '404':
          description: Channel does not exist
    put:
      summary: Set the audio input level for the selected channel
      description: Only one property (gain or normalised) is required for setting. If both are provided, gain will be used.
      parameters:
        - name: channelIndex
          in: path
          description: The index of the channel that its input is being controlled. (Channels index from 0)
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/level'
      responses:
        '204':
          description: No Content
        '400':
          description: Invalid input or value out of range
        '404':
          description: Channel does not exist
  /audio/channel/{channelIndex}/phantomPower:
    get:
      summary: Get the audio input phantom power status for the selected channel
      parameters:
        - name: channelIndex
          in: path
          description: The index of the channel that its input is being controlled. (Channels index from 0)
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Currently set phantom power for the selected channel
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/phantomPower'
        '404':
          description: Channel does not exist
    put:
      summary: Set the audio phantom power for the selected channel
      parameters:
        - name: channelIndex
          in: path
          description: The index of the channel that its input is being controlled. (Channels index from 0)
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/phantomPower'
      responses:
        '204':
          description: No Content
        '400':
          description: Phantom power is not supported for this input
        '404':
          description: Channel does not exist
  /audio/channel/{channelIndex}/padding:
    get:
      summary: Get the audio input padding status for the selected channel
      parameters:
        - name: channelIndex
          in: path
          description: The index of the channel that its input is being controlled. (Channels index from 0)
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Currently set padding for the selected channel
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/padding'
        '404':
          description: Channel does not exist
    put:
      summary: Set the audio input padding for the selected channel
      parameters:
        - name: channelIndex
          in: path
          description: The index of the channel that its input is being controlled. (Channels index from 0)
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/padding'
      responses:
        '204':
          description: No Content
        '400':
          description: Padding is not supported or is forced for this input
        '404':
          description: Channel does not exist
  /audio/channel/{channelIndex}/lowCutFilter:
    get:
      summary: Get the audio input low cut filter status for the selected channel
      parameters:
        - name: channelIndex
          in: path
          description: The index of the channel that its input is being controlled. (Channels index from 0)
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Currently set low cut filter for the selected channel
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lowCutFilter'
        '404':
          description: Channel does not exist
    put:
      summary: Set the audio input low cut filter for the selected channel
      parameters:
        - name: channelIndex
          in: path
          description: The index of the channel that its input is being controlled. (Channels index from 0)
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/lowCutFilter'
      responses:
        '204':
          description: No Content
        '400':
          description: Low cut filter is not supported for this input
        '404':
          description: Channel does not exist
  /audio/channel/{channelIndex}/available:
    get:
      summary: Get the audio input's current availability for the selected channel. If unavailable, the source will be muted
      parameters:
        - name: channelIndex
          in: path
          description: The index of the channel that its input is being controlled. (Channels index from 0)
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Currently set availability for the selected channel
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/available'
        '404':
          description: Channel does not exist
components:
  schemas:
    input:
      type: object
      properties:
        input:
          type: string
          description: Audio input source and type
    inputDescription:
      type: object
      properties:
        description:
          type: object
          properties:
            gainRange:
              type: object
              properties:
                Min:
                  description: The minimum gain value in dB
                  type: number
                  format: float
                Max:
                  description: The maximum gain value in dB
                  type: number
                  format: float
            capabilities:
              type: object
              properties:
                PhantomPower:
                  description: Input supports setting of phantom power
                  type: boolean
                LowCutFilter:
                  description: Input supports setting of low cut filter
                  type: boolean
                Padding:
                  type: object
                  properties:
                    available:
                      description: Input supports setting of padding
                      type: boolean
                    forced:
                      description: Padding is forced to be set for the input
                      type: boolean
                    value:
                      description: Value of the padding in dB
                      type: number
                      format: float
    level:
      type: object
      properties:
        gain:
          type: number
          format: float
          description: Gain value in dB
        normalised:
          type: number
          format: float
          description: Normalised level value between 0.0 and 1.0
    phantomPower:
      type: object
      properties:
        enabled:
          type: boolean
          description: Phantom power enabled state
    padding:
      type: object
      properties:
        enabled:
          type: boolean
          description: Padding enabled state
    lowCutFilter:
      type: object
      properties:
        enabled:
          type: boolean
          description: Low cut filter enabled state
    available:
      type: object
      properties:
        available:
          type: boolean
          description: Whether the input is currently available