openapi: 3.0.1
info:
  title: Color Correction Control API
  description: API For controlling the color correction on Blackmagic Design products based on DaVinci Resolve Color Corrector
  version: 0.2.0
servers:
- url: /control/api/v1
paths:
  /colorCorrection/lift:
    get:
      summary: Get color correction lift
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lift'
    put:
      summary: Set color correction lift
      description: All parameters are optional. Any omitted parameter will remain unchanged.
      requestBody:
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/Lift'
      responses:
        204:
          description: No Content
  /colorCorrection/gamma:
    get:
      summary: Get color correction gamma
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gamma'
    put:
      summary: Set color correction gamma
      description: All parameters are optional. Any omitted parameter will remain unchanged.
      requestBody:
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/Gamma'
      responses:
        204:
          description: No Content
  /colorCorrection/gain:
    get:
      summary: Get color correction gain
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Gain'
    put:
      summary: Set color correction gain
      description: All parameters are optional. Any omitted parameter will remain unchanged.
      requestBody:
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/Gain'
      responses:
        204:
          description: No Content
  /colorCorrection/offset:
    get:
      summary: Get color correction offset
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Offset'
    put:
      summary: Set color correction offset
      description: All parameters are optional. Any omitted parameter will remain unchanged.
      requestBody:
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/Offset'
      responses:
        204:
          description: No Content
  /colorCorrection/contrast:
    get:
      summary: Get color correction contrast
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Contrast'
    put:
      summary: Set color correction contrast
      description: All parameters are optional. Any omitted parameter will remain unchanged.
      requestBody:
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/Contrast'
      responses:
        204:
          description: No Content
  /colorCorrection/color:
    get:
      summary: Get color correction color properties
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Color'
    put:
      summary: Set color correction color properties
      description: All parameters are optional. Any omitted parameter will remain unchanged.
      requestBody:
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/Color'
      responses:
        204:
          description: No Content
  /colorCorrection/lumaContribution:
    get:
      summary: Get color correction luma contribution
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LumaContribution'
    put:
      summary: Set color correction luma contribution
      description: All parameters are optional. Any omitted parameter will remain unchanged.
      requestBody:
        content:
          application/json:
              schema:
                $ref: '#/components/schemas/LumaContribution'
      responses:
        204:
          description: No Content

components:
  schemas:
    Lift:
      type: object
      properties:
        red:
          type: number
          format: float
          maximum: 2.0
          minimum: -2.0
          description: Red lift component. If omitted, value remains unchanged.
        green:
          type: number
          format: float
          maximum: 2.0
          minimum: -2.0
          description: Green lift component. If omitted, value remains unchanged.
        blue:
          type: number
          format: float
          maximum: 2.0
          minimum: -2.0
          description: Blue lift component. If omitted, value remains unchanged.
        luma:
          type: number
          format: float
          maximum: 2.0
          minimum: -2.0
          description: Luma lift component. If omitted, value remains unchanged.
    Gamma:
      type: object
      properties:
        red:
          type: number
          format: float
          maximum: 4.0
          minimum: -4.0
          description: Red gamma component. If omitted, value remains unchanged.
        green:
          type: number
          format: float
          maximum: 4.0
          minimum: -4.0
          description: Green gamma component. If omitted, value remains unchanged.
        blue:
          type: number
          format: float
          maximum: 4.0
          minimum: -4.0
          description: Blue gamma component. If omitted, value remains unchanged.
        luma:
          type: number
          format: float
          maximum: 4.0
          minimum: -4.0
          description: Luma gamma component. If omitted, value remains unchanged.
    Gain:
      type: object
      properties:
        red:
          type: number
          format: float
          maximum: 16.0
          minimum: 0.0
          description: Red gain component. If omitted, value remains unchanged.
        green:
          type: number
          format: float
          maximum: 16.0
          minimum: 0.0
          description: Green gain component. If omitted, value remains unchanged.
        blue:
          type: number
          format: float
          maximum: 16.0
          minimum: 0.0
          description: Blue gain component. If omitted, value remains unchanged.
        luma:
          type: number
          format: float
          maximum: 16.0
          minimum: 0.0
          description: Luma gain component. If omitted, value remains unchanged.
    Offset:
      type: object
      properties:
        red:
          type: number
          format: float
          maximum: 8.0
          minimum: -8.0
          description: Red offset component. If omitted, value remains unchanged.
        green:
          type: number
          format: float
          maximum: 8.0
          minimum: -8.0
          description: Green offset component. If omitted, value remains unchanged.
        blue:
          type: number
          format: float
          maximum: 8.0
          minimum: -8.0
          description: Blue offset component. If omitted, value remains unchanged.
        luma:
          type: number
          format: float
          maximum: 8.0
          minimum: -8.0
          description: Luma offset component. If omitted, value remains unchanged.
    Contrast:
      type: object
      properties:
        pivot:
          type: number
          format: float
          maximum: 1.0
          minimum: 0.0
          description: Contrast pivot point. If omitted, value remains unchanged.
        adjust:
          type: number
          format: float
          maximum: 2.0
          minimum: 0.0
          description: Contrast adjustment. If omitted, value remains unchanged.
    Color:
      type: object
      properties:
        hue:
          type: number
          format: float
          maximum: 1.0
          minimum: -1.0
          description: Color hue adjustment. If omitted, value remains unchanged.
        saturation:
          type: number
          format: float
          maximum: 2.0
          minimum: 0.0
          description: Color saturation adjustment. If omitted, value remains unchanged.
    LumaContribution:
      type: object
      properties:
        lumaContribution:
          type: number
          format: float
          maximum: 1.0
          minimum: 0.0
          description: Luma contribution value. If omitted, value remains unchanged.