openapi: 3.0.1
info:
  title: Event Control API
  description: API For working with built-in websocket.
  version: 1.0.0
servers:
- url: /control/api/v1
tags:
- name: Event
  description: Event Control API
paths:
  /event/list:
    get:
      summary: Get the list of events that can be subscribed to using the websocket API.
      tags:
      - Event
      responses:
        200:
          description: Websocket API events list.
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/eventsList'
components:
  schemas:
    eventsList:
      type: object
      properties:
        events:
          type: array
          description: List of events that can be subscribed to using the websocket API.
          items:
            type: string
